apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
  namespace: dev
# automountServiceAccountToken: false

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-read
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-read-bind
  namespace: dev
subjects:
- kind: ServiceAccount
  name: server
  namespace: dev
roleRef:
  kind: Role
  name: server-read
  apiGroup: rbac.authorization.k8s.io