apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: "ingress.example.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          serviceName: goserver-service
          servicePort: 80
  tls:
   - hosts:
     - "ingress.example.com"
     secretName: letsencrypt-tls